export const filterButtons = [
    "All Matches",
    "Double Matches",
    "1.5 Goals",
    "Correct Scores",
    "Draw",
    "2.5 Goals",
    "BTTS",
    "Singles",
    "1st Half Goals",
    "Multi Goals",
    "Win Either Half",
    "HT/FT",
    "Combo",
    "Most Scoring Half",
    "Corners",
    "Cards",
    "Fouls",
    "Offsides",
    "Player Stats",
];
