export const matchesData = [
    {
        home: {
            name: "Germany",
            flag: "https://flagcdn.com/de.svg",
        },
        away: { name: "Scotland", flag: "https://flagcdn.com/gb-sct.svg" },
        time: "20:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.30" },
            { title: "X", odds: "1.30" },
            { title: "2", odds: "1.30" },
            { title: "1X", odds: "1.30" },
            { title: "2X", odds: "1.30" },
            { title: "12", odds: "1.30" },
            { title: "O2.5", odds: "1.30" },
            { title: "U2.5", odds: "1.30" },
        ],
        oddsRight: [
            { title: "1", odds: "57%" },
            { title: "X", odds: "31%" },
            { title: "2", odds: "12%" },
        ],
        prediction: { ft: "1X", outcome: "2-1" },
    },
    {
        home: { name: "Spain", flag: "https://flagcdn.com/es.svg" },
        away: { name: "France", flag: "https://flagcdn.com/fr.svg" },
        time: "18:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.45" },
            { title: "X", odds: "2.10" },
            { title: "2", odds: "1.75" },
            { title: "1X", odds: "1.35" },
            { title: "2X", odds: "1.45" },
            { title: "12", odds: "1.60" },
            { title: "O2.5", odds: "1.50" },
            { title: "U2.5", odds: "1.40" },
        ],
        oddsRight: [
            { title: "1", odds: "60%" },
            { title: "X", odds: "25%" },
            { title: "2", odds: "15%" },
        ],
        prediction: { ft: "1X", outcome: "1-0" },
    },
    {
        home: { name: "Italy", flag: "https://flagcdn.com/it.svg" },
        away: { name: "Portugal", flag: "https://flagcdn.com/pt.svg" },
        time: "21:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.60" },
            { title: "X", odds: "2.00" },
            { title: "2", odds: "1.90" },
            { title: "1X", odds: "1.50" },
            { title: "2X", odds: "1.60" },
            { title: "12", odds: "1.70" },
            { title: "O2.5", odds: "1.60" },
            { title: "U2.5", odds: "1.50" },
        ],
        oddsRight: [
            { title: "1", odds: "55%" },
            { title: "X", odds: "30%" },
            { title: "2", odds: "15%" },
        ],
        prediction: { ft: "1", outcome: "2-1" },
    },
    {
        home: { name: "Netherlands", flag: "https://flagcdn.com/nl.svg" },
        away: { name: "Belgium", flag: "https://flagcdn.com/be.svg" },
        time: "19:00 PM",
        oddsLeft: [
            { title: "1", odds: "2.00" },
            { title: "X", odds: "2.50" },
            { title: "2", odds: "3.00" },
            { title: "1X", odds: "1.80" },
            { title: "2X", odds: "2.10" },
            { title: "12", odds: "2.20" },
            { title: "O2.5", odds: "2.00" },
            { title: "U2.5", odds: "1.80" },
        ],
        oddsRight: [
            { title: "1", odds: "45%" },
            { title: "X", odds: "30%" },
            { title: "2", odds: "25%" },
        ],
        prediction: { ft: "2", outcome: "1-2" },
    },
    {
        home: { name: "Argentina", flag: "https://flagcdn.com/ar.svg" },
        away: { name: "Brazil", flag: "https://flagcdn.com/br.svg" },
        time: "22:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.75" },
            { title: "X", odds: "2.25" },
            { title: "2", odds: "2.00" },
            { title: "1X", odds: "1.60" },
            { title: "2X", odds: "1.80" },
            { title: "12", odds: "1.90" },
            { title: "O2.5", odds: "1.75" },
            { title: "U2.5", odds: "1.65" },
        ],
        oddsRight: [
            { title: "1", odds: "50%" },
            { title: "X", odds: "25%" },
            { title: "2", odds: "25%" },
        ],
        prediction: { ft: "1", outcome: "2-1" },
    },
    {
        home: { name: "England", flag: "https://flagcdn.com/gb-eng.svg" },
        away: { name: "Italy", flag: "https://flagcdn.com/it.svg" },
        time: "20:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.85" },
            { title: "X", odds: "2.20" },
            { title: "2", odds: "1.95" },
            { title: "1X", odds: "1.70" },
            { title: "2X", odds: "1.85" },
            { title: "12", odds: "1.90" },
            { title: "O2.5", odds: "1.80" },
            { title: "U2.5", odds: "1.75" },
        ],
        oddsRight: [
            { title: "1", odds: "55%" },
            { title: "X", odds: "30%" },
            { title: "2", odds: "15%" },
        ],
        prediction: { ft: "1", outcome: "2-0" },
    },
    {
        home: { name: "Portugal", flag: "https://flagcdn.com/pt.svg" },
        away: { name: "Netherlands", flag: "https://flagcdn.com/nl.svg" },
        time: "19:45 PM",
        oddsLeft: [
            { title: "1", odds: "1.70" },
            { title: "X", odds: "2.40" },
            { title: "2", odds: "2.20" },
            { title: "1X", odds: "1.60" },
            { title: "2X", odds: "1.80" },
            { title: "12", odds: "1.85" },
            { title: "O2.5", odds: "1.75" },
            { title: "U2.5", odds: "1.65" },
        ],
        oddsRight: [
            { title: "1", odds: "50%" },
            { title: "X", odds: "30%" },
            { title: "2", odds: "20%" },
        ],
        prediction: { ft: "1X", outcome: "1-1" },
    },
    {
        home: { name: "Chile", flag: "https://flagcdn.com/cl.svg" },
        away: { name: "Colombia", flag: "https://flagcdn.com/co.svg" },
        time: "20:30 PM",
        oddsLeft: [
            { title: "1", odds: "2.10" },
            { title: "X", odds: "2.70" },
            { title: "2", odds: "2.40" },
            { title: "1X", odds: "1.90" },
            { title: "2X", odds: "2.10" },
            { title: "12", odds: "2.30" },
            { title: "O2.5", odds: "2.00" },
            { title: "U2.5", odds: "1.85" },
        ],
        oddsRight: [
            { title: "1", odds: "45%" },
            { title: "X", odds: "35%" },
            { title: "2", odds: "20%" },
        ],
        prediction: { ft: "X", outcome: "1-1" },
    },
    {
        home: { name: "Japan", flag: "https://flagcdn.com/jp.svg" },
        away: { name: "South Korea", flag: "https://flagcdn.com/kr.svg" },
        time: "18:30 PM",
        oddsLeft: [
            { title: "1", odds: "1.95" },
            { title: "X", odds: "2.50" },
            { title: "2", odds: "2.30" },
            { title: "1X", odds: "1.75" },
            { title: "2X", odds: "1.90" },
            { title: "12", odds: "2.00" },
            { title: "O2.5", odds: "1.85" },
            { title: "U2.5", odds: "1.80" },
        ],
        oddsRight: [
            { title: "1", odds: "52%" },
            { title: "X", odds: "28%" },
            { title: "2", odds: "20%" },
        ],
        prediction: { ft: "1", outcome: "2-0" },
    },
    {
        home: { name: "Australia", flag: "https://flagcdn.com/au.svg" },
        away: { name: "New Zealand", flag: "https://flagcdn.com/nz.svg" },
        time: "17:00 PM",
        oddsLeft: [
            { title: "1", odds: "1.80" },
            { title: "X", odds: "2.60" },
            { title: "2", odds: "2.50" },
            { title: "1X", odds: "1.70" },
            { title: "2X", odds: "1.90" },
            { title: "12", odds: "2.10" },
            { title: "O2.5", odds: "1.90" },
            { title: "U2.5", odds: "1.80" },
        ],
        oddsRight: [
            { title: "1", odds: "50%" },
            { title: "X", odds: "30%" },
            { title: "2", odds: "20%" },
        ],
        prediction: { ft: "1", outcome: "1-0" },
    },
    {
        home: { name: "USA", flag: "https://flagcdn.com/us.svg" },
        away: { name: "Mexico", flag: "https://flagcdn.com/mx.svg" },
        time: "23:00 PM",
        oddsLeft: [
            { title: "1", odds: "2.20" },
            { title: "X", odds: "2.90" },
            { title: "2", odds: "2.60" },
            { title: "1X", odds: "1.90" },
            { title: "2X", odds: "2.20" },
            { title: "12", odds: "2.30" },
            { title: "O2.5", odds: "2.10" },
            { title: "U2.5", odds: "1.90" },
        ],
        oddsRight: [
            { title: "1", odds: "48%" },
            { title: "X", odds: "32%" },
            { title: "2", odds: "20%" },
        ],
        prediction: { ft: "X", outcome: "1-1" },
    },
];
